# Generated by Django 5.1.5 on 2025-01-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='post',
        ),
    ]
